@host=localhost
@port=4004
@protocol=http

###POST operation to upload invoice pdf

POST {{protocol}}://{{host}}:{{port}}/odata/v2/media/MediaFile
Content-Type: application/pdf
slug: invoice.pdf

< ./myPDF.pdf

###
POST {{protocol}}://{{host}}:{{port}}/odata/v4/media/MediaFile HTTP/1.1
Content-Type: application/json

{
 "ID":"7a6b186b-57fd-4baa-9098-4906b4800275"
}

###
PUT {{protocol}}://{{host}}:{{port}}/odata/v4/media/MediaFile(7a6b186b-57fd-4baa-9098-4906b4800275)/content HTTP/1.1
Content-Type: application/pdf
slug: myPDF.pdf



< ./myPDF.pdf

###
GET {{protocol}}://{{host}}:{{port}}/odata/v4/media/MediaFile(7a6b186b-57fd-4baa-9098-4906b4800275)/content
Content-Type: application/octet-stream

###
GET {{protocol}}://{{host}}:{{port}}/odata/v4/media/MediaFile(7a6b186b-57fd-4baa-9098-4906b4800275)/content
Content-Disposition: 'attachment; filename="myPDF.pdf"'

